spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/places
    username: postgis
    password: postgis
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
